import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Download, ExternalLink, Award } from "lucide-react";
import { createClient } from "@/utils/supabase/server";

export const metadata = {
  title: "Manage Certificates | CodeInternX Admin",
};

export default async function AdminCertificatesPage() {
  const supabase = await createClient();

  const { data: certificates, error } = await supabase
    .from("certificates")
    .select(`
      id,
      certificate_id,
      issue_date,
      profiles ( full_name, email ),
      programs ( title )
    `)
    .order("issue_date", { ascending: false });

  if (error) {
    console.error("Error fetching certificates:", error);
  }

  // Formatting date
  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
    });
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-slate-900">Manage Certificates</h1>
          <p className="text-muted-foreground mt-1">View and issue completion certificates to students.</p>
        </div>
        <Button className="shrink-0 bg-blue-600 hover:bg-blue-700 text-white">
          <Award className="w-4 h-4 mr-2" />
          Issue New Certificate
        </Button>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Issued Certificates</CardTitle>
          <CardDescription>
            A list of all verifiable certificates generated by the platform.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="rounded-md border border-slate-200">
            <Table>
              <TableHeader className="bg-slate-50">
                <TableRow>
                  <TableHead className="font-semibold text-slate-900">Certificate ID</TableHead>
                  <TableHead className="font-semibold text-slate-900">Student</TableHead>
                  <TableHead className="font-semibold text-slate-900 hidden md:table-cell">Program</TableHead>
                  <TableHead className="font-semibold text-slate-900 hidden md:table-cell">Issue Date</TableHead>
                  <TableHead className="font-semibold text-slate-900 text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {certificates && certificates.length > 0 ? (
                  certificates.map((cert: any) => (
                    <TableRow key={cert.id}>
                      <TableCell className="font-medium text-slate-900">
                        <Badge variant="outline" className="bg-slate-100 font-mono text-xs">
                          {cert.certificate_id}
                        </Badge>
                      </TableCell>
                      <TableCell className="text-slate-900 font-medium">
                        {cert.profiles?.full_name}
                        <div className="text-xs text-slate-500 font-normal">
                          {cert.profiles?.email}
                        </div>
                      </TableCell>
                      <TableCell className="text-slate-600 hidden md:table-cell">
                        {cert.programs?.title}
                      </TableCell>
                      <TableCell className="text-slate-600 hidden md:table-cell">
                        {formatDate(cert.issue_date)}
                      </TableCell>
                      <TableCell className="text-right">
                        <div className="flex justify-end gap-2">
                          <Button size="icon" variant="ghost" title="View Public Verify Page">
                            <ExternalLink className="w-4 h-4 text-slate-500" />
                          </Button>
                          <Button size="icon" variant="ghost" title="Download PDF">
                            <Download className="w-4 h-4 text-blue-600" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))
                ) : (
                  <TableRow>
                    <TableCell colSpan={5} className="h-24 text-center text-slate-500">
                      No certificates issued yet.
                    </TableCell>
                  </TableRow>
                )}
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
